# Generated by Django 6.0.3 on 2026-04-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angajat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_angajat', models.CharField(max_length=100)),
                ('salariu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cnp', models.CharField(max_length=13, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cafenea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_cafenea', models.CharField(max_length=100)),
                ('adresa', models.CharField(max_length=200)),
                ('oras', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_client', models.CharField(max_length=100)),
                ('nr_tranzactii', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Produs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_produs', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.CharField(max_length=50)),
                ('stoc_curent', models.IntegerField(default=0)),
                ('stoc_minim', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Tranzactie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pret_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_tranzactie', models.DateTimeField(auto_now_add=True)),
                ('metoda_plata', models.CharField(max_length=20)),
                ('angajat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGICA_DATABASE.angajat')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LOGICA_DATABASE.client')),
            ],
        ),
        migrations.CreateModel(
            name='TranzactieProdus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantitate', models.IntegerField(default=1)),
                ('pret_la_moment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGICA_DATABASE.produs')),
                ('tranzactie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LOGICA_DATABASE.tranzactie')),
            ],
        ),
    ]
